### ISSUE TITLE
Setting up Paths

### ISSUE THREAD

**Issue by thuhoainguyen** [thuhoainguyen/kits23#12]
@anhtuduong I already created a `.zshrc` file as instructed:
```
~ 43s
base ❯ nano ~/Projects/FBK/kits23/envar.zshrc

~ 16s
base ❯ cat ~/Projects/FBK/kits23/envar.zshrc
export nnUNet_raw="/media/fabian/nnUNet_raw"
export nnUNet_preprocessed="/media/fabian/nnUNet_preprocessed"
export nnUNet_results="/media/fabian/nnUNet_results"
```

Right now, I am doing the **Setting up Paths** step. They said in the document as follow:
# Setting up Paths

nnU-Net relies on environment variables to know where raw data, preprocessed data and trained model weights are stored. 
To use the full functionality of nnU-Net, the following three environment variables must be set:

1) `nnUNet_raw`: This is where you place the raw datasets. This folder will have one subfolder for each dataset names 
DatasetXXX_YYY where XXX is a 3-digit identifier (such as 001, 002, 043, 999, ...) and YYY is the (unique) 
dataset name. The datasets must be in nnU-Net format, see [here](dataset_format.md).

    Example tree structure:
    ```
    nnUNet_raw/Dataset001_NAME1
    ├── dataset.json
    ├── imagesTr
    │   ├── ...
    ├── imagesTs
    │   ├── ...
    └── labelsTr
        ├── ...
    nnUNet_raw/Dataset002_NAME2
    ├── dataset.json
    ├── imagesTr
    │   ├── ...
    ├── imagesTs
    │   ├── ...
    └── labelsTr
        ├── ...
    ```
But I don't know how to automatically set the dataset names like the format. Can you help me ?

**Comment by thuhoainguyen** [comment]
@anhtuduong Sure !! Thank you

**Comment by anhtuduong** [comment]
@thuhoainguyen Oh by the way can you:
```
git add envar.zshrc
```
```
git commit -m "something"
```
```
git push
```

I also need this file, thankss

**Comment by anhtuduong** [comment]
@thuhoainguyen I have converted the dataset format for nnUNet:

![Image](https://github.com/thuhoainguyen/kits23/assets/76017474/c47a4a59-10f7-400f-be4b-324e080310b7)

I also setup a folder with the nnUNet model and all requirements to run. So next phase is:
1. Copy my setup folder to your hard drive.
2. Try to copy it to Optimus machine. (I don't know how)
3. Run the nnUNet model on Optimus.
4. Evaluate the test cases to obtain the metrics (can run on Optimus or your laptop).
