### ISSUE TITLE
Dataset path in Optimus

### ISSUE THREAD

**Issue by thuhoainguyen** [thuhoainguyen/kits23#15]
@anhtuduong This is the terminal code I copy paste here:
```
hnguyen@optimus:~$ cd ..
hnguyen@optimus:/home$ cd /data/hnguyen/
hnguyen@optimus:/data/hnguyen$ ls
```
kits23_training  myenv  setup.py  trial.py
```
hnguyen@optimus:/data/hnguyen$ cd kits23_training/
hnguyen@optimus:/data/hnguyen/kits23_training$ ls
```
nnUNet_preprocessed  nnUNet_raw  nnUNet_results

**Comment by anhtuduong** [comment]
Good good! Let me setup. You can focus on your project exam these days!
