### ISSUE TITLE
Understanding .gitignore

### ISSUE THREAD

**Issue by anhtuduong** [thuhoainguyen/kits23#2]
@thuhoainguyen  The full dataset is about 52GB, which is huge. By using `.gitignore` we can ignore the image data (large file) and avoid pushing it to github. That's why in the `.gitignore` there's a line:

```
dataset/*/*imaging.nii.gz
```

So not all the files with extension `nii.gz` are ignored, but only the files with the suffix `imaging.nii.gz` are ignored.

**Comment by thuhoainguyen** [comment]
I see, the file `imaging.nii.gz` is 4.5 times larger than all the other files (227MB to 50MB) in each case folder.

**Comment by anhtuduong** [comment]
That file is the image data, and the rest are annotations.

**Comment by thuhoainguyen** [comment]
ok ! got it
