### ISSUE TITLE
Update hist path in the code

### ISSUE THREAD

**Issue by anhtuduong** [thuhoainguyen/kits23#4]
Now you have the histogram file, please update the variable `hist_path` in the code. @thuhoainguyen

**Comment by thuhoainguyen** [comment]
@anhtuduong I updated the variable in the code as below:

Before:
<img width="556" alt="image" src="https://github.com/thuhoainguyen/kits23/assets/165920750/ad213452-6d41-4bcc-bfbd-545c2f54c800">

After:
<img width="282" alt="image" src="https://github.com/thuhoainguyen/kits23/assets/165920750/711df1b4-3136-44a4-bc7a-75191a701cc7">

As I understand, I will have to change all the original Window version path like "C:\\Data\\2023_09_KidneyCancer\\kits23-main" into new variables. 
However, I'm not sure what this path should be updated into ? Please help :(
`'C:\\Data\\2023_09_KidneyCancer\\kits23-main'`

All The code block cd to kits23-main that have that path are shown below:
<img width="769" alt="image" src="https://github.com/thuhoainguyen/kits23/assets/165920750/55b4a70f-6469-411e-8a32-ece8cfb72c21">
<img width="739" alt="image" src="https://github.com/thuhoainguyen/kits23/assets/165920750/61949267-aaba-456d-b11d-0ac47e4ed268">
<img width="842" alt="image" src="https://github.com/thuhoainguyen/kits23/assets/165920750/f9f6ea53-ae26-4646-a19d-34f50e5f768e">
<img width="899" alt="image" src="https://github.com/thuhoainguyen/kits23/assets/165920750/53e1db62-06a1-4aab-b971-ae714c0a7590">

**Comment by anhtuduong** [comment]
@thuhoainguyen  First, if you capture the screenshot of the code and put it here as an image, it will be difficult for me to copy that code to comment. Instead you should copy the code and paste it here within the ``` block, for example:

![Image](https://github.com/thuhoainguyen/kits23/assets/76017474/b57ecff4-347e-4e45-afa0-6da156ebca85)

--------------

`dataset_path` is the folder name of the dataset, and `hist_path` is the histogram file name. So if you set:
```
dataset_path = 'dataset_path'
hist_path = 'hist_path'
```
The script won't find any folder name 'dataset_path' and won't find any file name 'hist_path'. Instead:
```
dataset_path = 'dataset' # The correct folder name of the dataset
hist_path = 'hists/histogram_counts.npy'
```

-----------

`'C:\\Data\\2023_09_KidneyCancer\\kits23-main'` refers to the project root folder. They are trying to create a new folder with suffix `date-time` to store new things. Try to look up GG to understand how you can create new folder with new suffix from the root project folder.

**Comment by thuhoainguyen** [comment]
@anhtuduong I understand it as change completely the code `os.path.join('C:\\Data\\2023_09_KidneyCancer\\kits23-main', self.date_str, case_id, "slices")` to something else. What I supposed to do was just to change the path `C:\\Data\\2023_09_KidneyCancer\\kits23-main` to something so this will be easier for me.

**Comment by thuhoainguyen** [comment]
@anhtuduong As I research on the Internet, the code `os.path.join('C:\\Data\\2023_09_KidneyCancer\\kits23-main', self.date_str, case_id, "slices")` will join the path of the main folder + date + case + slices.

**Comment by anhtuduong** [comment]
@thuhoainguyen I have resolve all the wrong paths for you. Use `git pull` to update
