### ISSUE TITLE
Add debugging informations

### ISSUE THREAD

**Issue by anhtuduong** [thuhoainguyen/kits23#5]
When executing any code in the terminal, we want to print out the more info the better for understanding and debugging the execution. We can just use function `print()` in python to print out the info we need. In practice we should have a way to print out the info but with different level: `INFO`, `WARNING`, `ERROR`. And all the informations will be put it into a log file so we can inspect that whenever we want.
I will help you integrate this in the code.

**Comment by anhtuduong** [comment]
@thuhoainguyen I just added an utility called log.py. Remember to use `git pull` to pull the update i made before continuing to work!

**Comment by thuhoainguyen** [comment]
@anhtuduong I tried git status to see what you changed, however, I see no log.py file added:
<img width="560" alt="image" src="https://github.com/thuhoainguyen/kits23/assets/165920750/2daf5e17-a1a4-4d19-b910-5a0b2f321763">

**Comment by thuhoainguyen** [comment]
@anhtuduong the file name "dataset_missingfiles" is the dataset file, I just renamed it because I am trying to download again the dataset file from terminal which didn't work out.

**Comment by anhtuduong** [comment]
@thuhoainguyen You should not rename that

**Comment by anhtuduong** [comment]
@thuhoainguyen I implemented the log.py but you have to use command `git pull` to pull the update. For now you should not worry about this debugging utility because I will do it for you.

**Comment by thuhoainguyen** [comment]
Ah I got that. I just `git pull` it 
<img width="653" alt="image" src="https://github.com/thuhoainguyen/kits23/assets/165920750/1b242840-656b-4192-bc5a-c9b118e2bfb9">

**Comment by thuhoainguyen** [comment]
@anhtuduong I am not sure how to execute the `log.py` file, can you be more specific on what should i do now?

**Comment by thuhoainguyen** [comment]
@anhtuduong I see what is the log file will do in the `resample_image.py` file. It will show the info or basically what each code line is doing so we can keep track of the workflow, the error, etc.
