### ISSUE TITLE
Install library with virtual environment

### ISSUE THREAD

**Issue by anhtuduong** [thuhoainguyen/kits23#7]
In the project root terminal, run:
```
git pull
```
```
python3 -m venv venv
```
```
source venv/bin/activate
```
```
pip3 install -e .
```

**Comment by thuhoainguyen** [comment]
@anhtuduong i just run the code you provided, then this error appeared when i executed the last code line:


![Image](https://github.com/thuhoainguyen/kits23/assets/165920750/e5d410e0-eb79-4615-b162-4b42966b73f9)

**Comment by anhtuduong** [comment]
@thuhoainguyen because you are not in the project root folder. The location you should be running is `FBK/kits23` not `FBK/kits23/kits23`

**Comment by thuhoainguyen** [comment]
@anhtuduong Alright, I think i successfully install library with virtual environment.


![Image](https://github.com/thuhoainguyen/kits23/assets/165920750/d7f84666-03cf-48b4-bf02-e4ac584f4f68)

**Comment by anhtuduong** [comment]
@thuhoainguyen Can you run this
```
python3 -m termcolor
```
to make sure you have `termcolor` installed

**Comment by thuhoainguyen** [comment]
Yes! 


![Image](https://github.com/thuhoainguyen/kits23/assets/165920750/6628679c-b55b-4440-b9d7-163dd59f9d82)


![Image](https://github.com/thuhoainguyen/kits23/assets/165920750/ca563a5a-81d9-4a9c-b3a2-d18f234389a0)

**Comment by thuhoainguyen** [comment]
@anhtuduong today I try to run the preprocessing file but it said no module named "termcolor". I don't know why


![Image](https://github.com/thuhoainguyen/kits23/assets/165920750/4d5b8d58-6e3d-4ca3-bdad-c4291f931340)
